rootProject.name = 'ZMusic'
include('zmusic-plugin')
include('zmusic-addon')

// NMS
include(
        "zmusic-nms",
        "zmusic-nms:zmusic-nms-core",
        "zmusic-nms:zmusic-nms-legacy",
        "zmusic-nms:zmusic-nms-1.17",
        "zmusic-nms:zmusic-nms-1.18",
        "zmusic-nms:zmusic-nms-1.19",
        "zmusic-nms:zmusic-nms-1.20",
        "zmusic-nms:zmusic-nms-paper-1.21.4",
        "zmusic-nms:zmusic-nms-paper-1.21.8",
        "zmusic-nms:zmusic-nms-paper-1.21.11",
        "zmusic-nms:zmusic-nms-paper-26.2"
)
