name: ZMusic
main: cn.iqianye.MinecraftPlugins.ZMusic.Main
version: 0.1-beta
author: 真心
description: 点歌系统
depend: [AudioBuffer,ActionBarAPI,Vault]
commands:
  zm:
    usage: /zm help
    description: 点歌系统主命令
permissions:
  ZMusic.use:
    default: true
    description: 普通玩家使用权限
  ZMusic.admin:
    default: op
    description: 管理员权限