name: Sync Code

on:
  push:
    branches:
      - "v4"
      - "v2"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Sync to Codeberg
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          git remote add codeberg "https://zhenxin:${CODEBERG_TOKEN}@codeberg.org/starhui-dev/zmusic-plugin.git"
          git push codeberg --all --force
          git push codeberg --tags --force

      - name: Sync to CNB
        env:
          CNB_TOKEN: ${{ secrets.CNB_TOKEN }}
        run: |
          git remote add cnb "https://cnb:${CNB_TOKEN}@cnb.cool/starhui-dev/zmusic-plugin.git"
          git push cnb --all --force
          git push cnb --tags --force
